name: "roberta-baseline"
description: "Full fine-tuning of roberta base."
paper: "https://arxiv.org/pdf/1907.11692.pdf"
data:
  data_dir: "data"
  train_file: "train.txt"
  dev_file: "dev.txt"
  test_file: "test.txt"
model:  # model-specific configuration
  type: raw  # type of the model to use. Currently supported: ["adapter", "bitfit"]
training_args:  # training arguments passed to the trainer
  learning_rate: 0.00001
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  weight_decay: 0.1
  num_train_epochs: 10
  warmup_percentage: 0.06
